version: '3.9'

services:
  db:
    image: postgres:16
    container_name: eventapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eventsDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Events.API/Dockerfile
    container_name: eventapp-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=eventsDb;Username=postgres;Password=root"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
